apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-config
  labels:
    app: eazypay-api
data:
  appsettings.json: |
    {
      "Logging": {
        "LogLevel": {
          "Default": "Information",
          "Microsoft": "Warning",
          "Microsoft.Hosting.Lifetime": "Information"
        }
      },
      "AllowedHosts": "*",
      "ConnectionStrings": {
        "DefaultConnection": "Server=db_server;Database=eazypaydb;User Id=user;Password=password;"
      }
    }